# Generated by Django 3.2.8 on 2021-11-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='potluck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='potluck_dish_contains_nuts',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='potluck_dish_course',
            field=models.CharField(blank=True, choices=[('M', 'Main dish'), ('A', 'Appetizer'), ('D', 'Dessert')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='potluck_dish_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='potluck_dish_is_spicy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='potluck_dish_is_vegan',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='potluck_dish_is_vegetarian',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
