# Generated by Django 3.2.8 on 2021-10-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20211010_2316"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="295 Stockholm St, Brooklyn, NY 11237", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="tagline",
            field=models.CharField(default="Best party every", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
