# Generated by Django 3.2.8 on 2021-10-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20211011_0207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="emoji",
        ),
        migrations.RemoveField(
            model_name="rsvp",
            name="session",
        ),
    ]
