# Generated by Django 3.2.8 on 2021-10-11 05:11

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20211011_0354"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 10, 11, 5, 11, 4, 877638, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 10, 11, 5, 11, 11, 691208, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rsvp",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
